import { z } from "zod";

export const applicantSchema = z.object({
  cibil_score: z.number().int().min(300).max(900),
  cibil_pl_score: z.number().int().min(0).max(900),
  pl_write_off: z.boolean(),
  home_loan_wo: z.boolean(),
  consumer_loan_wo: z.boolean(),
  agri_loan_wo: z.boolean(),
  msme_loan_wo: z.boolean(),
  auto_loan_wo: z.boolean(),
  cc_write_off: z.boolean(),
  wo_amount: z.number().min(0),
  dpd: z.number().int().min(0),
  loan_enquiry: z.boolean(),
  age: z.number().int().min(18).max(100),
  age_last_emi_salaried: z.number().int().min(0).max(100),
  age_last_emi_se: z.number().int().min(0).max(100),
  existing_account: z.boolean(),
  existing_car_loan: z.boolean(),
  rented_house_salaried: z.boolean(),
  rented_house_self_employed: z.boolean(),
  resi_cum_office_owned: z.boolean(),
  resi_cum_office_rented: z.boolean(),
  resi_office_separate_rented: z.boolean(),
  without_guarantor: z.boolean(),
  with_guarantor: z.boolean(),
  unmarried: z.boolean(),
  nri_pio: z.boolean(),
  minimum_stay_period_nri: z.number().int().min(0),
  salaried: z.boolean(),
  agriculture: z.boolean(),
  employment_firm: z.boolean(),
  employment_pvt_ltd: z.boolean(),
  employment_public_ltd: z.boolean(),
  employment_govt: z.boolean(),
  employment_psu: z.boolean(),
  total_experience: z.number().min(0).max(60),
  current_experience: z.number().min(0).max(60),
  salary_payment_mode_cash: z.boolean(),
  salary_payment_mode_bank_credit: z.boolean(),
  no_income_proof: z.boolean(),
  rental_income_non_itr: z.boolean(),
  rental_income_itr: z.boolean(),
  rental_income_not_reflecting: z.boolean(),
  rental_income_reflecting_in_bank: z.boolean(),
  income: z.number().min(0),
  business_income: z.number().min(0),
  se_current_itr: z.number().min(0),
  se_previous_itr: z.number().min(0),
  business_itr_years: z.number().int().min(0).max(10),
  self_employed: z.boolean(),
  self_employed_itr_filled: z.boolean(),
  itr_not_filed: z.boolean(),
  business_proof: z.string(),
  proprietorship: z.boolean(),
  partnership_firm: z.boolean(),
  private_limited: z.boolean(),
  public_limited: z.boolean(),
  currently_outstanding: z.boolean(),
  emi_income: z.number().min(0).max(1),
  huf: z.boolean(),
  form_16_years: z.number().int().min(0).max(10),
  co_applicant_age_brother: z.boolean(),
  co_applicant_age_sister: z.boolean(),
  co_applicant_income_brother: z.boolean(),
  co_applicant_income_father: z.boolean(),
  co_applicant_income_mother: z.boolean(),
  co_applicant_income_sister: z.boolean(),

  salary_mode: z.enum(["Bank Credit", "Cash"]).optional(),
});

export type ApplicantInput = z.infer<typeof applicantSchema>;

/** A sensible, eligible-by-default starting applicant. */
export const DEFAULT_APPLICANT: ApplicantInput = {
  cibil_score: 750,
  cibil_pl_score: 0,
  pl_write_off: false,
  home_loan_wo: false,
  consumer_loan_wo: false,
  agri_loan_wo: false,
  msme_loan_wo: false,
  auto_loan_wo: false,
  cc_write_off: false,
  wo_amount: 0,
  dpd: 0,
  loan_enquiry: false,
  age: 30,
  age_last_emi_salaried: 60,
  age_last_emi_se: 65,
  existing_account: true,
  existing_car_loan: true,
  rented_house_salaried: false,
  rented_house_self_employed: false,
  resi_cum_office_owned: true,
  resi_cum_office_rented: false,
  resi_office_separate_rented: false,
  without_guarantor: false,
  with_guarantor: false,
  unmarried: false,
  nri_pio: false,
  minimum_stay_period_nri: 0,
  salaried: true,
  agriculture: false,
  employment_firm: false,
  employment_pvt_ltd: true,
  employment_public_ltd: false,
  employment_govt: false,
  employment_psu: false,
  total_experience: 5,
  current_experience: 2,
  salary_payment_mode_cash: false,
  salary_payment_mode_bank_credit: true,
  no_income_proof: false,
  rental_income_non_itr: false,
  rental_income_itr: true,
  rental_income_not_reflecting: false,
  rental_income_reflecting_in_bank: true,
  income: 50000,
  business_income: 0,
  se_current_itr: 0,
  se_previous_itr: 0,
  business_itr_years: 0,
  self_employed: false,
  self_employed_itr_filled: false,
  itr_not_filed: false,
  business_proof: "Mandatory",
  proprietorship: false,
  partnership_firm: false,
  private_limited: false,
  public_limited: false,
  currently_outstanding: false,
  emi_income: 0,
  huf: false,
  form_16_years: 2,
  co_applicant_age_brother: false,
  co_applicant_age_sister: false,
  co_applicant_income_brother: false,
  co_applicant_income_father: false,
  co_applicant_income_mother: false,
  co_applicant_income_sister: false,

  salary_mode: "Bank Credit",
};

export const SALARY_MODES = ["Bank Credit", "Cash"] as const;
export const BUSINESS_PROOF_OPTIONS = ["Mandatory", "Not Mandatory"] as const;
